# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permohonan',
            name='perihal',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
