# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIS', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('kelas', models.CharField(choices=[('XI RPL 1', 'XI RPL 1'), ('XI RPL 2', 'XI RPL 2'), ('XI RPL 3', 'XI RPL 3'), ('XI TKJ 1', 'XI TKJ 1'), ('XI TKJ 2', 'XI TKJ 2'), ('XI TKJ 3', 'XI TKJ 3'), ('XI TKJ 4', 'XI TKJ 4')], max_length=8)),
                ('program_ahli', models.CharField(choices=[('Teknik Komputer & Jaringan', 'Teknik Komputer & Jaringan'), ('Rekayasa Perangkat Lunak', 'Rekayasa Perangkat Lunak')], max_length=26)),
            ],
        ),
    ]
