# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20180521_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(choices=[('XI.RPL-1', 'XI.RPL-1'), ('XI.RPL-2', 'XI.RPL-2'), ('XI.RPL-3', 'XI.RPL-3'), ('XI.TKJ-1', 'XI.TKJ-1'), ('XI.TKJ-2', 'XI.TKJ-2'), ('XI.TKJ-3', 'XI.TKJ-3'), ('XI.TKJ-4', 'XI.TKJ-4')], max_length=15),
        ),
    ]
