# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20180626_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='pkl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(choices=[('XII.RPL-1', 'XII.RPL-1'), ('XII.RPL-2', 'XII.RPL-2'), ('XII.RPL-3', 'XII.RPL-3'), ('XII.TKJ-1', 'XII.TKJ-1'), ('XII.TKJ-2', 'XII.TKJ-2'), ('XII.TKJ-3', 'XII.TKJ-3'), ('XII.TKJ-4', 'XII.TKJ-4')], max_length=15),
        ),
    ]
