# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20180702_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstansiTKJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
