# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karya_ilmiah', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyailmiah',
            name='nama',
        ),
        migrations.DeleteModel(
            name='KaryaIlmiah',
        ),
    ]
