# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0008_pembimbing'),
        ('karya_ilmiah', '0002_auto_20180816_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaryaIlmiah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tanggal_acc', models.DateField()),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Siswa')),
                ('pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Pembimbing')),
            ],
        ),
    ]
