# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karya_ilmiah', '0003_karyailmiah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyailmiah',
            name='judul',
            field=models.TextField(),
        ),
    ]
